---
title: Actvcontent
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sales@actvcontent.com
description: Actvcontent makes software to enable real-time factory-wide visibility
  throughout the manufacturing process.
baseurl: actvcontent.siteleaf.net
url: actvcontent.siteleaf.net
markdown: kramdown
